swagger: "2.0"
info:
  version: 1.0.0
  title: Example
  description: An example API

host: localhost:3000

basePath: '/'

consumes:
  - application/json
produces:
  - application/json

paths:
  "/examples":
    get:
      description: Returns an empty array
      responses:
        default:
          description: Returns an empty array
          schema:
            type: array
            items:
              $ref: example
          headers:
            last-modified:
              type: string
              description: The date/time 
